// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchPlacesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Radius               uint32   `protobuf:"varint,3,opt,name=radius" json:"radius,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	MinPrice             string   `protobuf:"bytes,5,opt,name=minPrice" json:"minPrice,omitempty"`
	MaxPrice             string   `protobuf:"bytes,6,opt,name=maxPrice" json:"maxPrice,omitempty"`
	OpenNow              bool     `protobuf:"varint,7,opt,name=openNow" json:"openNow,omitempty"`
	PlaceType            string   `protobuf:"bytes,8,opt,name=placeType" json:"placeType,omitempty"`
	PageToken            string   `protobuf:"bytes,9,opt,name=pageToken" json:"pageToken,omitempty"`
	Vendor               string   `protobuf:"bytes,10,opt,name=vendor" json:"vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPlacesRequest) Reset()         { *m = SearchPlacesRequest{} }
func (m *SearchPlacesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchPlacesRequest) ProtoMessage()    {}
func (*SearchPlacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{0}
}
func (m *SearchPlacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesRequest.Unmarshal(m, b)
}
func (m *SearchPlacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesRequest.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesRequest.Merge(dst, src)
}
func (m *SearchPlacesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesRequest.Size(m)
}
func (m *SearchPlacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesRequest proto.InternalMessageInfo

func (m *SearchPlacesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchPlacesRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *SearchPlacesRequest) GetRadius() uint32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *SearchPlacesRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SearchPlacesRequest) GetMinPrice() string {
	if m != nil {
		return m.MinPrice
	}
	return ""
}

func (m *SearchPlacesRequest) GetMaxPrice() string {
	if m != nil {
		return m.MaxPrice
	}
	return ""
}

func (m *SearchPlacesRequest) GetOpenNow() bool {
	if m != nil {
		return m.OpenNow
	}
	return false
}

func (m *SearchPlacesRequest) GetPlaceType() string {
	if m != nil {
		return m.PlaceType
	}
	return ""
}

func (m *SearchPlacesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *SearchPlacesRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

type LatLng struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLng) Reset()         { *m = LatLng{} }
func (m *LatLng) String() string { return proto.CompactTextString(m) }
func (*LatLng) ProtoMessage()    {}
func (*LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{1}
}
func (m *LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLng.Unmarshal(m, b)
}
func (m *LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLng.Marshal(b, m, deterministic)
}
func (dst *LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLng.Merge(dst, src)
}
func (m *LatLng) XXX_Size() int {
	return xxx_messageInfo_LatLng.Size(m)
}
func (m *LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_LatLng proto.InternalMessageInfo

func (m *LatLng) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LatLng) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type SearchPlacesResponse struct {
	Results              []*SearchPlacesResponse_PlacesSearchResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	HtmlAttributes       []string                                   `protobuf:"bytes,2,rep,name=htmlAttributes" json:"htmlAttributes,omitempty"`
	NextPageToken        string                                     `protobuf:"bytes,3,opt,name=nextPageToken" json:"nextPageToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *SearchPlacesResponse) Reset()         { *m = SearchPlacesResponse{} }
func (m *SearchPlacesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchPlacesResponse) ProtoMessage()    {}
func (*SearchPlacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2}
}
func (m *SearchPlacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse.Unmarshal(m, b)
}
func (m *SearchPlacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse.Merge(dst, src)
}
func (m *SearchPlacesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse.Size(m)
}
func (m *SearchPlacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse proto.InternalMessageInfo

func (m *SearchPlacesResponse) GetResults() []*SearchPlacesResponse_PlacesSearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchPlacesResponse) GetHtmlAttributes() []string {
	if m != nil {
		return m.HtmlAttributes
	}
	return nil
}

func (m *SearchPlacesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type SearchPlacesResponse_PlacesSearchResult struct {
	FormattedAddress     string                                                   `protobuf:"bytes,1,opt,name=formattedAddress" json:"formattedAddress,omitempty"`
	Geometry             *SearchPlacesResponse_PlacesSearchResult_AddressGeometry `protobuf:"bytes,2,opt,name=geometry" json:"geometry,omitempty"`
	Name                 string                                                   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Icon                 string                                                   `protobuf:"bytes,4,opt,name=icon" json:"icon,omitempty"`
	PlaceID              string                                                   `protobuf:"bytes,5,opt,name=placeID" json:"placeID,omitempty"`
	Scope                string                                                   `protobuf:"bytes,6,opt,name=scope" json:"scope,omitempty"`
	Rating               float32                                                  `protobuf:"fixed32,7,opt,name=rating" json:"rating,omitempty"`
	Types                []string                                                 `protobuf:"bytes,8,rep,name=types" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult{}
}
func (m *SearchPlacesResponse_PlacesSearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchPlacesResponse_PlacesSearchResult) ProtoMessage()    {}
func (*SearchPlacesResponse_PlacesSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0}
}
func (m *SearchPlacesResponse_PlacesSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetGeometry() *SearchPlacesResponse_PlacesSearchResult_AddressGeometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *SearchPlacesResponse_PlacesSearchResult) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type SearchPlacesResponse_PlacesSearchResult_AddressGeometry struct {
	Location             *LatLng                                               `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	LocationType         string                                                `protobuf:"bytes,2,opt,name=locationType" json:"locationType,omitempty"`
	Bounds               *SearchPlacesResponse_PlacesSearchResult_LatLngBounds `protobuf:"bytes,3,opt,name=bounds" json:"bounds,omitempty"`
	Viewport             *SearchPlacesResponse_PlacesSearchResult_LatLngBounds `protobuf:"bytes,4,opt,name=viewport" json:"viewport,omitempty"`
	Types                []string                                              `protobuf:"bytes,5,rep,name=types" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_AddressGeometry{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_AddressGeometry) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_AddressGeometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 0}
}
func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AddressGeometry.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AddressGeometry.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AddressGeometry.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AddressGeometry.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AddressGeometry.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AddressGeometry proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) GetLocation() *LatLng {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) GetBounds() *SearchPlacesResponse_PlacesSearchResult_LatLngBounds {
	if m != nil {
		return m.Bounds
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) GetViewport() *SearchPlacesResponse_PlacesSearchResult_LatLngBounds {
	if m != nil {
		return m.Viewport
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_AddressGeometry) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type SearchPlacesResponse_PlacesSearchResult_LatLngBounds struct {
	Northeast            *LatLng  `protobuf:"bytes,1,opt,name=northeast" json:"northeast,omitempty"`
	Southwest            *LatLng  `protobuf:"bytes,2,opt,name=southwest" json:"southwest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_LatLngBounds{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_LatLngBounds) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_LatLngBounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 1}
}
func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_LatLngBounds.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_LatLngBounds.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_LatLngBounds.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_LatLngBounds.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_LatLngBounds.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_LatLngBounds proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) GetNortheast() *LatLng {
	if m != nil {
		return m.Northeast
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_LatLngBounds) GetSouthwest() *LatLng {
	if m != nil {
		return m.Southwest
	}
	return nil
}

type SearchPlacesResponse_PlacesSearchResult_OpeningHours struct {
	OpenNow              bool                                                          `protobuf:"varint,1,opt,name=openNow" json:"openNow,omitempty"`
	Periods              []*SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod `protobuf:"bytes,2,rep,name=periods" json:"periods,omitempty"`
	WeekDayText          []string                                                      `protobuf:"bytes,3,rep,name=weekDayText" json:"weekDayText,omitempty"`
	PermanentlyClose     bool                                                          `protobuf:"varint,4,opt,name=permanentlyClose" json:"permanentlyClose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                      `json:"-"`
	XXX_unrecognized     []byte                                                        `json:"-"`
	XXX_sizecache        int32                                                         `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_OpeningHours{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_OpeningHours) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_OpeningHours) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 2}
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHours.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHours.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_OpeningHours) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHours.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHours.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHours.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHours proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) GetOpenNow() bool {
	if m != nil {
		return m.OpenNow
	}
	return false
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) GetPeriods() []*SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod {
	if m != nil {
		return m.Periods
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) GetWeekDayText() []string {
	if m != nil {
		return m.WeekDayText
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHours) GetPermanentlyClose() bool {
	if m != nil {
		return m.PermanentlyClose
	}
	return false
}

type SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod struct {
	Open                 *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose `protobuf:"bytes,1,opt,name=open" json:"open,omitempty"`
	Close                *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose `protobuf:"bytes,2,opt,name=close" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                       `json:"-"`
	XXX_unrecognized     []byte                                                         `json:"-"`
	XXX_sizecache        int32                                                          `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 3}
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) GetOpen() *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose {
	if m != nil {
		return m.Open
	}
	return nil
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod) GetClose() *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose {
	if m != nil {
		return m.Close
	}
	return nil
}

type SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose struct {
	Day                  int32    `protobuf:"varint,1,opt,name=day" json:"day,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 4}
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type SearchPlacesResponse_PlacesSearchResult_Photo struct {
	PhotoReference       string   `protobuf:"bytes,1,opt,name=photoReference" json:"photoReference,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width" json:"width,omitempty"`
	HtmlAttributes       []string `protobuf:"bytes,4,rep,name=htmlAttributes" json:"htmlAttributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_Photo) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_Photo{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_Photo) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_Photo) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 5}
}
func (m *SearchPlacesResponse_PlacesSearchResult_Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_Photo.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_Photo.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_Photo.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_Photo) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_Photo.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_Photo proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_Photo) GetPhotoReference() string {
	if m != nil {
		return m.PhotoReference
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult_Photo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SearchPlacesResponse_PlacesSearchResult_Photo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *SearchPlacesResponse_PlacesSearchResult_Photo) GetHtmlAttributes() []string {
	if m != nil {
		return m.HtmlAttributes
	}
	return nil
}

type SearchPlacesResponse_PlacesSearchResult_AltID struct {
	PlaceID              string   `protobuf:"bytes,1,opt,name=placeID" json:"placeID,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPlacesResponse_PlacesSearchResult_AltID) Reset() {
	*m = SearchPlacesResponse_PlacesSearchResult_AltID{}
}
func (m *SearchPlacesResponse_PlacesSearchResult_AltID) String() string {
	return proto.CompactTextString(m)
}
func (*SearchPlacesResponse_PlacesSearchResult_AltID) ProtoMessage() {}
func (*SearchPlacesResponse_PlacesSearchResult_AltID) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e14e9da45d8270ee, []int{2, 0, 6}
}
func (m *SearchPlacesResponse_PlacesSearchResult_AltID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AltID.Unmarshal(m, b)
}
func (m *SearchPlacesResponse_PlacesSearchResult_AltID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AltID.Marshal(b, m, deterministic)
}
func (dst *SearchPlacesResponse_PlacesSearchResult_AltID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AltID.Merge(dst, src)
}
func (m *SearchPlacesResponse_PlacesSearchResult_AltID) XXX_Size() int {
	return xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AltID.Size(m)
}
func (m *SearchPlacesResponse_PlacesSearchResult_AltID) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AltID.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlacesResponse_PlacesSearchResult_AltID proto.InternalMessageInfo

func (m *SearchPlacesResponse_PlacesSearchResult_AltID) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *SearchPlacesResponse_PlacesSearchResult_AltID) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchPlacesRequest)(nil), "api.SearchPlacesRequest")
	proto.RegisterType((*LatLng)(nil), "api.LatLng")
	proto.RegisterType((*SearchPlacesResponse)(nil), "api.SearchPlacesResponse")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult)(nil), "api.SearchPlacesResponse.PlacesSearchResult")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_AddressGeometry)(nil), "api.SearchPlacesResponse.PlacesSearchResult.AddressGeometry")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_LatLngBounds)(nil), "api.SearchPlacesResponse.PlacesSearchResult.LatLngBounds")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_OpeningHours)(nil), "api.SearchPlacesResponse.PlacesSearchResult.OpeningHours")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_OpeningHoursPeriod)(nil), "api.SearchPlacesResponse.PlacesSearchResult.OpeningHoursPeriod")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_OpeningHoursOpenClose)(nil), "api.SearchPlacesResponse.PlacesSearchResult.OpeningHoursOpenClose")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_Photo)(nil), "api.SearchPlacesResponse.PlacesSearchResult.Photo")
	proto.RegisterType((*SearchPlacesResponse_PlacesSearchResult_AltID)(nil), "api.SearchPlacesResponse.PlacesSearchResult.AltID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchPlacesClient is the client API for SearchPlaces service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchPlacesClient interface {
	SayHello(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error)
}

type searchPlacesClient struct {
	cc *grpc.ClientConn
}

func NewSearchPlacesClient(cc *grpc.ClientConn) SearchPlacesClient {
	return &searchPlacesClient{cc}
}

func (c *searchPlacesClient) SayHello(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error) {
	out := new(SearchPlacesResponse)
	err := c.cc.Invoke(ctx, "/api.SearchPlaces/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchPlaces service

type SearchPlacesServer interface {
	SayHello(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error)
}

func RegisterSearchPlacesServer(s *grpc.Server, srv SearchPlacesServer) {
	s.RegisterService(&_SearchPlaces_serviceDesc, srv)
}

func _SearchPlaces_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchPlacesServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SearchPlaces/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchPlacesServer).SayHello(ctx, req.(*SearchPlacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchPlaces_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SearchPlaces",
	HandlerType: (*SearchPlacesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SearchPlaces_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_e14e9da45d8270ee) }

var fileDescriptor_api_e14e9da45d8270ee = []byte{
	// 836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5f, 0x8f, 0x1b, 0x35,
	0x10, 0xd7, 0x26, 0xb7, 0xb9, 0x64, 0x72, 0xfd, 0x23, 0xd3, 0xa2, 0x65, 0xd5, 0x87, 0x28, 0x42,
	0x25, 0xa0, 0xea, 0x2a, 0x85, 0x07, 0x84, 0x04, 0x42, 0x57, 0x4e, 0xd0, 0x4a, 0x15, 0x04, 0xf7,
	0xa8, 0xca, 0xa3, 0x2f, 0x3b, 0xb7, 0x59, 0x75, 0x63, 0x6f, 0x6d, 0x6f, 0x73, 0x11, 0xe2, 0x05,
	0x89, 0x4f, 0xc0, 0x3b, 0x12, 0xdf, 0x05, 0xf1, 0x8e, 0xf8, 0x0a, 0x7c, 0x03, 0xbe, 0x00, 0xf2,
	0xd8, 0x9b, 0xdb, 0xdc, 0xa5, 0x0f, 0x07, 0xbc, 0xcd, 0x6f, 0xc6, 0x1e, 0x7b, 0x7e, 0xfe, 0xcd,
	0x18, 0x06, 0xa2, 0x2a, 0x0e, 0x2b, 0xad, 0xac, 0x62, 0x5d, 0x51, 0x15, 0xe9, 0xbd, 0x5c, 0xa9,
	0xbc, 0xc4, 0x87, 0xa2, 0x2a, 0x1e, 0x0a, 0x29, 0x95, 0x15, 0xb6, 0x50, 0xd2, 0xf8, 0x25, 0xe3,
	0x5f, 0x3b, 0xf0, 0xd6, 0x33, 0x14, 0x7a, 0xbe, 0x98, 0x95, 0x62, 0x8e, 0x86, 0xe3, 0xab, 0x1a,
	0x8d, 0x65, 0x77, 0x20, 0x7e, 0x55, 0xa3, 0x5e, 0x27, 0xd1, 0x28, 0x9a, 0x0c, 0xb8, 0x07, 0x2c,
	0x85, 0x7e, 0xa9, 0xe6, 0x94, 0x20, 0xe9, 0x50, 0x60, 0x83, 0xd9, 0xdb, 0xd0, 0xd3, 0x22, 0x2b,
	0x6a, 0x93, 0x74, 0x47, 0xd1, 0xe4, 0x06, 0x0f, 0x88, 0xf6, 0x08, 0x99, 0xd7, 0x22, 0xc7, 0x64,
	0x2f, 0xec, 0x09, 0xd8, 0xc5, 0x96, 0x85, 0x9c, 0xe9, 0x62, 0x8e, 0x49, 0xec, 0x63, 0x0d, 0xa6,
	0x98, 0x38, 0xf7, 0xb1, 0x5e, 0x88, 0x05, 0xcc, 0x12, 0xd8, 0x57, 0x15, 0xca, 0xaf, 0xd4, 0x2a,
	0xd9, 0x1f, 0x45, 0x93, 0x3e, 0x6f, 0x20, 0xbb, 0x07, 0x83, 0xca, 0x15, 0x72, 0xb2, 0xae, 0x30,
	0xe9, 0xd3, 0xb6, 0x0b, 0x07, 0x45, 0x45, 0x8e, 0x27, 0xea, 0x25, 0xca, 0x64, 0x10, 0xa2, 0x8d,
	0xc3, 0x55, 0xf0, 0x1a, 0x65, 0xa6, 0x74, 0x02, 0x14, 0x0a, 0x68, 0xfc, 0x00, 0x7a, 0x4f, 0x85,
	0x7d, 0x2a, 0x73, 0x76, 0x1b, 0xba, 0xa5, 0xb0, 0xc4, 0x49, 0xc4, 0x9d, 0x49, 0x1e, 0x99, 0x13,
	0x19, 0xce, 0x23, 0xf3, 0xf1, 0xdf, 0x43, 0xb8, 0xb3, 0xcd, 0xa8, 0xa9, 0x94, 0x34, 0xc8, 0xbe,
	0x80, 0x7d, 0x8d, 0xa6, 0x2e, 0xad, 0x49, 0xa2, 0x51, 0x77, 0x32, 0x9c, 0x3e, 0x38, 0x74, 0x4f,
	0xb5, 0x6b, 0xed, 0xa1, 0x87, 0x3e, 0xc4, 0x69, 0x13, 0x6f, 0x36, 0xb3, 0xfb, 0x70, 0x73, 0x61,
	0x97, 0xe5, 0x91, 0xb5, 0xba, 0x38, 0xad, 0x2d, 0x9a, 0xa4, 0x33, 0xea, 0x4e, 0x06, 0xfc, 0x92,
	0x97, 0xbd, 0x0b, 0x37, 0x24, 0x9e, 0xdb, 0xd9, 0xa6, 0xe0, 0x2e, 0x55, 0xb5, 0xed, 0x4c, 0x7f,
	0x03, 0x60, 0x57, 0x4f, 0x63, 0x1f, 0xc0, 0xed, 0x33, 0xa5, 0x97, 0xc2, 0x5a, 0xcc, 0x8e, 0xb2,
	0x4c, 0xa3, 0x31, 0x41, 0x0a, 0x57, 0xfc, 0xec, 0x05, 0xf4, 0x73, 0x54, 0x4b, 0xb4, 0x7a, 0x4d,
	0x44, 0x0c, 0xa7, 0x9f, 0x5c, 0xa7, 0xb2, 0xc3, 0x90, 0xe7, 0xcb, 0x90, 0x83, 0x6f, 0xb2, 0x31,
	0x06, 0x7b, 0x52, 0x2c, 0x31, 0xdc, 0x9c, 0x6c, 0xe7, 0x2b, 0xe6, 0x4a, 0x06, 0x2d, 0x91, 0xed,
	0xf4, 0x40, 0x8f, 0xfc, 0xe4, 0x38, 0xc8, 0xa8, 0x81, 0x4e, 0xc7, 0x66, 0xae, 0xaa, 0x46, 0x42,
	0x1e, 0x78, 0xad, 0xda, 0x42, 0xe6, 0x24, 0x9f, 0x0e, 0x0f, 0xc8, 0xad, 0xb6, 0xeb, 0x0a, 0x4d,
	0xd2, 0x27, 0x46, 0x3d, 0x48, 0x7f, 0xe9, 0xc0, 0xad, 0x4b, 0x77, 0x64, 0xef, 0xb5, 0x3a, 0x21,
	0xa2, 0x9a, 0x87, 0x54, 0xb3, 0x17, 0x4a, 0xab, 0x2d, 0xc6, 0x70, 0xd0, 0xd8, 0xa4, 0x49, 0xdf,
	0x36, 0x5b, 0x3e, 0xf6, 0x0d, 0xf4, 0x4e, 0x55, 0x2d, 0x33, 0xdf, 0x3a, 0xc3, 0xe9, 0xc7, 0xd7,
	0xa2, 0xcf, 0x1f, 0xf9, 0x88, 0x12, 0xf0, 0x90, 0x88, 0x7d, 0x0b, 0xfd, 0xd7, 0x05, 0xae, 0x2a,
	0xa5, 0x2d, 0x31, 0xf5, 0x9f, 0x92, 0x6e, 0x52, 0x5d, 0x10, 0x14, 0xb7, 0x09, 0xca, 0xe0, 0xa0,
	0xbd, 0x9e, 0xbd, 0x0f, 0x03, 0xa9, 0xb4, 0x5d, 0xa0, 0x30, 0x76, 0x17, 0x3b, 0x17, 0x51, 0xb7,
	0xd4, 0xa8, 0xda, 0x2e, 0x56, 0x68, 0x6c, 0x10, 0xcf, 0xf6, 0xd2, 0x4d, 0x34, 0xfd, 0x23, 0x82,
	0x83, 0xaf, 0x2b, 0x94, 0x85, 0xcc, 0x1f, 0xab, 0x5a, 0x9b, 0xf6, 0x14, 0x88, 0xb6, 0xa7, 0xc0,
	0x77, 0xb0, 0x5f, 0xa1, 0x2e, 0x54, 0xe6, 0x7b, 0x63, 0x38, 0xfd, 0xec, 0x5a, 0xc5, 0xb7, 0x4f,
	0x99, 0x51, 0x1e, 0xde, 0xe4, 0x63, 0x23, 0x18, 0xae, 0x10, 0x5f, 0x1e, 0x8b, 0xf5, 0x09, 0x9e,
	0xdb, 0xa4, 0x4b, 0x3c, 0xb4, 0x5d, 0xae, 0x75, 0x2a, 0xd4, 0x4b, 0x21, 0x51, 0xda, 0x72, 0xfd,
	0x79, 0xa9, 0x8c, 0x1f, 0x7c, 0x7d, 0x7e, 0xc5, 0x9f, 0xfe, 0x1e, 0x01, 0xbb, 0x7a, 0x1a, 0x7b,
	0x0e, 0x7b, 0xae, 0x94, 0xc0, 0xdd, 0xa3, 0x7f, 0x7d, 0x79, 0x67, 0xd3, 0x41, 0x9c, 0xf2, 0xb1,
	0x17, 0x10, 0xcf, 0xe9, 0x3e, 0x9d, 0xff, 0x2d, 0xb1, 0x4f, 0x98, 0x7e, 0x0a, 0x77, 0x77, 0xc6,
	0xdd, 0x80, 0xcc, 0x84, 0xff, 0x46, 0x62, 0xee, 0x4c, 0xd7, 0xc0, 0xb6, 0x58, 0x36, 0x9d, 0x40,
	0x76, 0xfa, 0x53, 0x04, 0xf1, 0x6c, 0xe1, 0xfe, 0xac, 0xfb, 0x70, 0xb3, 0x72, 0x06, 0xc7, 0x33,
	0xd4, 0x28, 0xe7, 0x18, 0xc6, 0xce, 0x25, 0xaf, 0x6b, 0xe1, 0x05, 0x16, 0xf9, 0xc2, 0xab, 0x26,
	0xe6, 0x01, 0x39, 0x85, 0xae, 0x8a, 0xcc, 0x2e, 0xa8, 0x95, 0x62, 0xee, 0xc1, 0x8e, 0x99, 0xb9,
	0xb7, 0x6b, 0x66, 0xa6, 0x1f, 0x41, 0x7c, 0x54, 0xda, 0x27, 0xc7, 0xed, 0x89, 0x12, 0xbd, 0x61,
	0xa2, 0x74, 0x5a, 0x13, 0x65, 0x7a, 0x06, 0x07, 0x6d, 0x1e, 0xd9, 0x73, 0xe8, 0x3f, 0x13, 0xeb,
	0xc7, 0x58, 0x96, 0x8a, 0x25, 0x3b, 0x68, 0xa6, 0x5f, 0x36, 0x7d, 0xe7, 0x8d, 0x0f, 0x30, 0xbe,
	0xfb, 0xe3, 0x9f, 0x7f, 0xfd, 0xdc, 0xb9, 0xc5, 0x6e, 0xd0, 0xc7, 0xfd, 0xbd, 0xff, 0x8a, 0x7e,
	0x38, 0xed, 0xd1, 0xb7, 0xfd, 0xe1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x96, 0xcd, 0x3c, 0x72,
	0xe6, 0x07, 0x00, 0x00,
}
